server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.50.133.143:3306/cloud_security?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234.Com
  data:
    redis:
      host: 10.50.133.145
      port: 6379
      database: 9
      password: 1234.com

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.security.entity
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

jwt:
  secret: your-secret-key-here-must-be-at-least-256-bits
  access-token-expiration: 3600 # 1 hour
  refresh-token-expiration: 86400 # 24 hours